name: alburhaan
description: "alburhaan"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: any
  json_annotation: ^4.4.0
  webview_flutter: ^4.0.7
  webview_flutter_android: ^3.13.0
  webview_flutter_platform_interface: ^2.10.0
  shared_preferences: ^2.1.1
  win32: ^5.14.0
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  cached_network_image: ^3.2.0
  build_runner: ^2.1.12
  json_serializable: ^6.2.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # Example for custom fonts (uncomment and modify if needed):
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
